<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CLONG01923" name="com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test" tests="1" failures="1" timestamp="24 Aug 2017 05:05:57 GMT" time="1.072" errors="0">
  <testcase name="loginSuccessFunction" time="1.072" classname="com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test">
    <failure type="java.lang.AssertionError" message="跳进frame: [ name: body] 失败">
      <![CDATA[java.lang.AssertionError: 跳进frame: [ name: body] 失败
	at org.testng.Assert.fail(Assert.java:93)
	at com.demo.test.utils.SeleniumUtil.switchFrame(SeleniumUtil.java:471)
	at com.demo.test.pageshelper.FramePageHelper.jumpInToFrame(FramePageHelper.java:14)
	at com.demo.test.pageshelper.LoginPageHelper.waitLoginPageLoad(LoginPageHelper.java:28)
	at com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test.loginSuccessFunction(LoginPage_001_LoginSuccessFunction_Test.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- loginSuccessFunction -->
</testsuite> <!-- com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test -->
