<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[result/screenshot/2017_08_24_13_05_55_loginSuccessFunction.jpg]]>
    </line>
    <line>
      <![CDATA[<img src="../../result/screenshot/2017_08_24_13_05_55_loginSuccessFunction.jpg"/>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="8801" started-at="2017-08-24T05:05:48Z" finished-at="2017-08-24T05:05:56Z">
    <groups>
    </groups>
    <test name="Login" duration-ms="8801" started-at="2017-08-24T05:05:48Z" finished-at="2017-08-24T05:05:56Z">
      <class name="com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test">
        <test-method status="PASS" signature="startTest(org.testng.ITestContext)[pri:0, instance:com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3d99d22e]" name="startTest" is-config="true" duration-ms="6161" started-at="2017-08-24T13:05:48Z" finished-at="2017-08-24T13:05:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@658c5a19]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="FAIL" signature="loginSuccessFunction(java.util.Map)[pri:0, instance:com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3d99d22e]" name="loginSuccessFunction" duration-ms="1072" started-at="2017-08-24T13:05:54Z" data-provider="testData" finished-at="2017-08-24T13:05:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PASSWORD=bean, USERNAME=jojo}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[跳进frame: [ name: body] 失败]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 跳进frame: [ name: body] 失败
	at org.testng.Assert.fail(Assert.java:93)
	at com.demo.test.utils.SeleniumUtil.switchFrame(SeleniumUtil.java:471)
	at com.demo.test.pageshelper.FramePageHelper.jumpInToFrame(FramePageHelper.java:14)
	at com.demo.test.pageshelper.LoginPageHelper.waitLoginPageLoad(LoginPageHelper.java:28)
	at com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test.loginSuccessFunction(LoginPage_001_LoginSuccessFunction_Test.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[result/screenshot/2017_08_24_13_05_55_loginSuccessFunction.jpg]]>
            </line>
            <line>
              <![CDATA[<img src="../../result/screenshot/2017_08_24_13_05_55_loginSuccessFunction.jpg"/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginSuccessFunction -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3d99d22e]" name="endTest" is-config="true" duration-ms="889" started-at="2017-08-24T13:05:56Z" finished-at="2017-08-24T13:05:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.demo.test.testcases.login.LoginPage_001_LoginSuccessFunction_Test -->
    </test> <!-- Login -->
  </suite> <!-- Suite -->
</testng-results>
